name: CI

env:
  HOST: ec2-3-111-58-220.ap-south-1.compute.amazonaws.com

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: deploy to ec2
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /home/ubuntu/deployments
          remote_host: "${{ env.HOST }}"
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"

  start-server:
    needs: deploy-to-ec2
    name: start server
    runs-on: ubuntu-latest
    timeout-minutes: 2
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: "${{ env.HOST }}"
          username: ubuntu
          key: "${{ secrets.SSH_PRIVATE_KEY }}"
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd deployments
            PID=$(ps -ef | grep node | grep -v grep | awk '{print $2}')
            if [ -z "$PID" ];
            then
                  echo "Process not running"
            else
                  echo "Killing process $PID"
                  kill -9 $PID
            fi
            npm install
            node index.js & exit 
