name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: deploy to ec2
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /home/ubuntu/deployments
          remote_host: ec2-3-111-58-220.ap-south-1.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
  start-server:
    needs: deploy-to-ec2
    name: start server
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ec2-3-111-58-220.ap-south-1.compute.amazonaws.com
          username: ubuntu
          key: "${{ secrets.SSH_PRIVATE_KEY }}"
          script: |
            cd deployments
            npm install
            node index.js
